#!/usr/bin/env bash
# Script that configure a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

redirect="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://meet.google.com;\n\t}"
sudo sed -i "55i $redirect" /etc/nginx/sites-available/default

sudo service nginx restart
