#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy


server_config=\
"

frontend lawrence-frontend
	bind *:80
	mode http
	default_backend lawrence-backend
backend lawrence-backend
	balance roundrobin
	server 339043-web-01 54.208.217.168:80 check
	server 339043-web-02 35.174.185.22:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
