#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy


server_config=\
"

frontend lawrence-frontend
	bind *:80
	mode http
	default_backend mavine-backend
backend mavine-backend
	balance roundrobin
	server 329062-web-01 54.160.67.249:80 check
	server 329062-web-02 34.207.63.31:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
