#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely
# Requirements: in between each iteration of the loop, add a sleep 2

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
