#!/usr/bin/env bash
# script to display the contents of the file /etc/passwd, using while loop + IFS.

while IFS=':' read -r username password uid gid info home shell
ido
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < "/etc/passwd"
