#!/usr/bin/env bash
# Display the time for 12hrs and 59 mins
hours=0
while [ $hours -le 12 ]
do 
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
done
