#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
# **** localhost resolves to 127.0.0.2
# **** facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.1         localhost" > ~/hosts.new
echo "157.240.11.35         facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
